### ISSUE TITLE
Error trying to set a column in the shape of a row

### ISSUE THREAD

**Issue by Socjon** [learn-co-curriculum/dsc-2-13-06-linalg-scalars-vectors-matrices-tensors-codealong#1]
> We can also use indexing to address and assign new values to elements of a matrix as shown below:
> 
> X[:, 0] = [11, 12, 13] # set column 0

The code above throws an error since `X` was defined as a `np.matrix`. The code should be instead `X[:, 0] = [[11], [12], [13]]`

**Comment by ShakeelRaja** [comment]
fixed error

**Comment by dymockb** [comment]
are you sure?

I'm getting an error with the updated code but the original works ok.  

X is defined as np.array.  Y was np.mat ?

**Comment by cyranothebard** [comment]
In the "Matrix Indexing" subsection the first line of the second code box should read X[:, 0] = [11, 12, 13] instead of X[:,0] = [[11], [12], [13]]. The current code raises the ValueError: setting an array element with a sequence. Since X is no longer defined as a np.matrix but just as a regular vector the previous fix no longer works and the code should revert to the original solution.
